In [1]:
import numpy as np

# Arithmetic Operations

In [8]:
array = np.array([[1, 2, 3], [4, 5, 6]])

In [9]:
array * array

array([[ 1,  4,  9],
       [16, 25, 36]])

In [10]:
array - array

array([[0, 0, 0],
       [0, 0, 0]])

In [11]:
1 / array

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [12]:
array ** 2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

# Boolean Operations

In [13]:
sq_array = array ** 2

In [14]:
sq_array > 6

array([[False, False,  True],
       [ True,  True,  True]])

In [15]:
array >= sq_array

array([[ True, False, False],
       [False, False, False]])