# Basics

The syntax for slicing arrays in NumPy is similar to that of the built-in lists. However, these work very differently. For instance:

* NumPy slices are simply **views** of the original array. This means that the data is not copied. Any changes you make to the view will be reflected in the original array. This is called **broadcasting**.
* You can assign both a scalar value and an iterable to a NumPy array, whereas only iterables can be assigned to Python lists.


## One-dimensional arrays

In [1]:
import numpy as np

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[3]

3

In [5]:
arr[3:6]

array([3, 4, 5])

Lets apply an *iterable* to the slice above.

*Note: The shape of the iterable being added e.g. the input array **must** be of the same shape as the slice!*

In [13]:
arr[3:6] = [15, 16, 17]

In [14]:
arr

array([ 0,  1,  2, 15, 16, 17,  6,  7,  8,  9])

See how the third, fourth and fifth index changes their values. Lets overwrite them with a scalar value using array slicing.

In [15]:
arr[3:6] = 20

In [16]:
arr

array([ 0,  1,  2, 20, 20, 20,  6,  7,  8,  9])

This operation is not possible in built-in lists!

    py_list = list(range(10))
    py_list[3:6] = 20
    
The code block above will raise the folloing error: `TypeError: can only assign an iterable`

Following the example above, if we do a full slice and assign a new value, the whole array will change:

In [17]:
arr[:] = 20

In [18]:
arr

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

### Copying an array using `copy` method

By using the `copy` method, we can copy the view into another array object and make modifications there while keeping the source array intact. Here, we will copy `arr` entirely into a new array object and change certain values. We can see at the end that `arr` still remains intact.

In [19]:
arr2 = arr[:].copy()

In [20]:
arr2[3:6] = 15

In [21]:
arr2

array([20, 20, 20, 15, 15, 15, 20, 20, 20, 20])

In [22]:
arr

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

## Multi-dimensional arrays

